# name: CI

# on:
#   pull_request:
#   push:
#     branches:
#       - main

# jobs:
#   CI:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Enable Corepack
#         run: corepack enable

#       - name: Update Yarn
#         run: corepack prepare yarn@4.0.2 --activate

#       - name: Install dependencies
#         run: yarn install --immutable

#       - name: TSlint
#         run: yarn tslint

#       - name: ESlint
#         run: yarn eslint

#       - name: Tests
#         run: yarn test
