name: Lint

on:
  pull_request:
  push:
    branches: [$default-branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable --ignore-scripts

      - name: Lint code
        run: yarn lint
